### PR TITLE
use modern scala-cli syntax everywhere

### PR DESCRIPTION
**Pull request by SethTisue**

### CODE REVIEW

**Comment by SethTisue** [comment]
(d766480 is actually necessary, or CI fails)

**Review by adpi2 — APPROVED** [review]
Thanks!

**Comment by som-snytt** [comment]
OMG it is totally viral. For perspective, I just started a quickie sbt project by hand, and used the test scope `something % "Test"` where the double-quotes are disabling. I don't know why a DSL should understand `Test` but not `"Test"`. One can imagine suitable conversions. Possibly, similar considerations are in play here.

**Comment by SethTisue** [comment]
> If we implement scala steward so far it only supports //> using lib as far as I am aware

is there a ticket on that? `using dep` is considered standard.

**Comment by armanbilge** [comment]
- https://github.com/scala-steward-org/scala-steward/issues/3174

**Comment by szymon-rd** [comment]
Are we sure that the syntax in 
```
//> using publish.developer adpi2|Adrien Piquerez|https://github.com/adpi2
```
will work? And not treat it as enumeration of `adpi2|Adrien`, `Piquerez|https://github.com/adpi2`?

**Pull request merged**
